apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-githubapps
  namespace: argocd
data:
  url: https://argocd.default.svc.cluster.local
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.insecure: "false"
  accounts.ghapp: login=sachindra-maharjan
  account.ghapp.tokens: $github-app-creds:githubAppID!$github-app-creds:githubAppInstallationID!$github-app-creds:githubAppPrivateKey
