replicaCount: 1

imagePullSecrets:
  - name: ghcr-auth-secret

image:
  repository: ghcr.io/schmhj/microservice-template
  pullPolicy: IfNotPresent
  tag: "v0.0.6"
  
service:
  type: NodePort
  port: 6000

